### ISSUE TITLE
Got error when using

### ISSUE THREAD

**Issue by studenton** [iamsudip/pysub-dl#3]
I get the following error:
`Traceback (most recent call last):
  File "/usr/local/bin/pysub-dl", line 216, in <module>
    search_sub(link)
  File "/usr/local/bin/pysub-dl", line 192, in search_sub
    alternate_search()
  File "/usr/local/bin/pysub-dl", line 65, in alternate_search
    print "{counter}. {key}".format(counter=num+1, key=key)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-52: ordinal not in range(128)
`

**Comment by iamsudip** [comment]
@studenton Looking into it. Can you please provide the movie name so that I can reproduce the issue?

**Comment by studenton** [comment]
@iamsudip Ironman

**Comment by iamsudip** [comment]
@studenton Couldn't reproduce the issue, can you tell what was the exact command? I tried with:
pysub-dl Ironman, which worked fine.

**Comment by studenton** [comment]
Now getting this: I typed pysub-dl Ironman

`Sorry! Please choose movie name from the list and enter the corresponding
index number.
1. Suits -  Fifth Season
2. The Fantastic Four
3. Dragon Nest: Warrior's Dawn
4. Imdb
5. Mr. Robot - First Season
`

**Comment by iamsudip** [comment]
@studenton That's what I also got. If you want Iron man subtitles you should do: `pysub-dl iron-man english`. Wondering how subscene's search algorithm works! If this issue is no longer exists, you can close the issue.

**Comment by studenton** [comment]
Thanks.
